LINK = "https://www.barco.com/en/clickshare/support/warranty-info"
COOKIE_BTN_ID = "onetrust-accept-btn-handler"
TEXTAREA_ID = "SerialNumber"
SPAN_CLASS = "field-validation-error"
RST_ITEM_CLASS = "c-warranty__result-item"